[build]
  command = "make build"
  publish = "public"
[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "https://github.com/touchSarcasticSad/NLP_Project_Serve"